[package]
name = "mouse-keyboard-input"
version = "0.1.0"
authors = ["fulara <ntszar@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }

[build-dependencies]
gcc = "*"